package com.example.rules

global Output output;
global org.apache.commons.lang.mutable.MutableInt counter;

declare Measure
    @role( event )
end

rule "Is of valid age"
when
    $a : Applicant( age < 18, valid == true )
    $c : Counter()
then
    modify( $c ) { setCount( $c.getCount() + 1 ) };
    modify ( $a ) { setValid( false ), setCount( $c.getCount() ) };
end

rule "Average in range"
when
    $av : Number(doubleValue > 53.0) from accumulate(Measure($value : value) over window:time(10m), average($value))
then
    System.out.println("Average " + $av);
    output.emit("Average value " + $av + " crossed threshold");
end
